name: seclsecl CD

on:
  push:
    branches:
      - main/dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      - name: zip build File
        run: zip -qq -r ./build-app.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp --region ap-northeast-2 ./build-app.zip s3://<seclsecl-deploy>/build-app.zip

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name seclsecl-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name seclsecl-deploy-group
          --s3-location bucket= seclsecl-deploy,key=build-app.zip,bundleType=zip
