name: seclsecl nestJS StartCI

on:
  workflow_dispatch:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev, main]

jobs:
  ci-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 설치 할 Node.js 버전 지정
          cache: 'npm' # npm 사용 시 'npm'

      # 의존성 패키지 설치하기
      - name: Install dependencies
        run: |

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Start server
        run: |
          npm start &
          sleep 10

      - name: Check server status
        run: curl -f http://localhost:3000/api/health
